In [91]:
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')
scoreList=[]

In [92]:
df=pd.read_csv('C:/Users/821vl/Downloads/bank+marketing/bank/bank-full.csv')
df.iloc[2:3,:]

age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
2  33;"entrepreneur";"married";"secondary";"no";2...

In [93]:
df.columns

Index(['age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"'], dtype='object')

In [94]:
# marital instead of martial
df=df['age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"'].str.split(';',expand=True)

Data Obtained from UC Irvine Machine Learning Repository
https://archive.ics.uci.edu/dataset/222/bank+marketing

Input variables:
   #bank client data:
   1 - age (numeric)
   2 - job : type of job (categorical: "admin.","unknown","unemployed","management","housemaid","entrepreneur","student",
                                       "blue-collar","self-employed","retired","technician","services") 
   3 - marital : marital status (categorical: "married","divorced","single"; note: "divorced" means divorced or widowed)
   4 - education (categorical: "unknown","secondary","primary","tertiary")
   5 - default: has credit in default? (binary: "yes","no")
   6 - balance: average yearly balance, in euros (numeric) 
   7 - housing: has housing loan? (binary: "yes","no")
   8 - loan: has personal loan? (binary: "yes","no")
   #related with the last contact of the current campaign:
   9 - contact: contact communication type (categorical: "unknown","telephone","cellular") 
  10 - day: last contact day of the month (numeric)
  11 - month: last contact month of year (categorical: "jan", "feb", "mar", ..., "nov", "dec")
  12 - duration: last contact duration, in seconds (numeric)
  #other attributes:
  13 - campaign: number of contacts performed during this campaign and for this client (numeric, includes last contact)
  14 - pdays: number of days that passed by after the client was last contacted from a previous campaign (numeric, -1 means client was not previously contacted)
  15 - previous: number of contacts performed before this campaign and for this client (numeric)
  16 - poutcome: outcome of the previous marketing campaign (categorical: "unknown","other","failure","success")

  Output variable (desired target):
  17 - y - has the client subscribed a term deposit? (binary: "yes","no")

In [95]:
df=df.rename(columns={0:'age',1:'job',2:'marital',3:'education',4:'default',5:'balance',6:'housing',7:'loan', \
                  8:'contact',9:'day',10:'month',11:'duration',12:'campaign',13:'pdays',14:'previous',15:'poutcome',16:'results',})
df

age             job     marital    education default balance housing  \
0      58    "management"   "married"   "tertiary"    "no"    2143   "yes"   
1      44    "technician"    "single"  "secondary"    "no"      29   "yes"   
2      33  "entrepreneur"   "married"  "secondary"    "no"       2   "yes"   
3      47   "blue-collar"   "married"    "unknown"    "no"    1506   "yes"   
4      33       "unknown"    "single"    "unknown"    "no"       1    "no"   
...    ..             ...         ...          ...     ...     ...     ...   
45206  51    "technician"   "married"   "tertiary"    "no"     825    "no"   
45207  71       "retired"  "divorced"    "primary"    "no"    1729    "no"   
45208  72       "retired"   "married"  "secondary"    "no"    5715    "no"   
45209  57   "blue-collar"   "married"  "secondary"    "no"     668    "no"   
45210  37  "entrepreneur"   "married"  "secondary"    "no"    2971    "no"   

        loan      contact day  month duration campaign pdays previous  \
0       "no"    "unknown"   5  "may"      261        1    -1        0   
1       "no"    "unknown"   5  "may"      151        1    -1        0   
2      "yes"    "unknown"   5  "may"       76        1    -1        0   
3       "no"    "unknown"   5  "may"       92        1    -1        0   
4       "no"    "unknown"   5  "may"      198        1    -1        0   
...      ...          ...  ..    ...      ...      ...   ...      ...   
45206   "no"   "cellular"  17  "nov"      977        3    -1        0   
45207   "no"   "cellular"  17  "nov"      456        2    -1        0   
45208   "no"   "cellular"  17  "nov"     1127        5   184        3   
45209   "no"  "telephone"  17  "nov"      508        4    -1        0   
45210   "no"   "cellular"  17  "nov"      361        2   188       11   

        poutcome results  
0      "unknown"    "no"  
1      "unknown"    "no"  
2      "unknown"    "no"  
3      "unknown"    "no"  
4      "unknown"    "no"  
...          ...     ...  
45206  "unknown"   "yes"  
45207  "unknown"   "yes"  
45208  "success"   "yes"  
45209  "unknown"    "no"  
45210    "other"    "no"  

[45211 rows x 17 columns]

In [96]:
df['job']=df['job'].str.replace('"',"")
df['marital']=df['marital'].str.replace('"',"")
df['education']=df['education'].str.replace('"',"")
df['default']=df['default'].str.replace('"',"")
df['housing']=df['loan'].str.replace('"',"")
df['contact']=df['contact'].str.replace('"',"")
df['poutcome']=df['poutcome'].str.replace('"',"")
df['results']=df['results'].str.replace('"',"")
df['loan']=df['loan'].str.replace('"',"")
df['month']=df['month'].str.replace('"',"")
df

age           job   marital  education default balance housing loan  \
0      58    management   married   tertiary      no    2143      no   no   
1      44    technician    single  secondary      no      29      no   no   
2      33  entrepreneur   married  secondary      no       2     yes  yes   
3      47   blue-collar   married    unknown      no    1506      no   no   
4      33       unknown    single    unknown      no       1      no   no   
...    ..           ...       ...        ...     ...     ...     ...  ...   
45206  51    technician   married   tertiary      no     825      no   no   
45207  71       retired  divorced    primary      no    1729      no   no   
45208  72       retired   married  secondary      no    5715      no   no   
45209  57   blue-collar   married  secondary      no     668      no   no   
45210  37  entrepreneur   married  secondary      no    2971      no   no   

         contact day month duration campaign pdays previous poutcome results  
0        unknown   5   may      261        1    -1        0  unknown      no  
1        unknown   5   may      151        1    -1        0  unknown      no  
2        unknown   5   may       76        1    -1        0  unknown      no  
3        unknown   5   may       92        1    -1        0  unknown      no  
4        unknown   5   may      198        1    -1        0  unknown      no  
...          ...  ..   ...      ...      ...   ...      ...      ...     ...  
45206   cellular  17   nov      977        3    -1        0  unknown     yes  
45207   cellular  17   nov      456        2    -1        0  unknown     yes  
45208   cellular  17   nov     1127        5   184        3  success     yes  
45209  telephone  17   nov      508        4    -1        0  unknown      no  
45210   cellular  17   nov      361        2   188       11    other      no  

[45211 rows x 17 columns]

In [97]:
#X and y labeling, just have to fix x and y
x=df.iloc[:,:-1]
y=df.iloc[:,-1:]

#This df is all variables as is, without any grouping(fairness)


In [98]:
x1=x.copy()
x1.loc[(x1['job']=='admin.') | (x1['job']=='entrepreneur') | (x1['job']=='management'),'job']='business'
x1.loc[(x1['job']=='blue-collar') | (x1['job']=='housemaid') | (x1['job']=='self-employed')| (x1['job']=='services')| (x1['job']=='technician'),'job']='other'
x1.loc[(x1['job']=='retired') | (x1['job']=='student') | (x1['job']=='unemployed') | (x1['job']=='unknown'),'job']='none'

x1.loc[(x1['marital']=='divorced') | (x1['marital']=='single'),'marital']='single'
x1.loc[(x1['marital']=='married'),'marital']='married'
#All other variables have 3-4 levels which seems not that bad. We can reduce if we want but job was the worst one to reduce

x1.loc[(x1['education']=='primary')|(x1['education']=='secondary')|(x1['education']=='unknown'),'education']='no_post'
x1.loc[(x1['education']=='tertiary'),'education']='post'


#Make Season: Add a season based on the month, will be used to see the most expensive seasons 
x1.loc[(x1['month']=='dec')|(x1['month']=='jan')|(x1['month']=='feb'),'season']='winter'
x1.loc[(x1['month']=='mar')|(x1['month']=='apr')|(x1['month']=='may'),'season']='spring'
x1.loc[(x1['month']=='jun')|(x1['month']=='jul')|(x1['month']=='aug'),'season']='summer'
x1.loc[(x1['month']=='sep')|(x1['month']=='oct')|(x1['month']=='nov'),'season']='fall'
x1


age       job  marital education default balance housing loan  \
0      58  business  married      post      no    2143      no   no   
1      44     other   single   no_post      no      29      no   no   
2      33  business  married   no_post      no       2     yes  yes   
3      47     other  married   no_post      no    1506      no   no   
4      33      none   single   no_post      no       1      no   no   
...    ..       ...      ...       ...     ...     ...     ...  ...   
45206  51     other  married      post      no     825      no   no   
45207  71      none   single   no_post      no    1729      no   no   
45208  72      none  married   no_post      no    5715      no   no   
45209  57     other  married   no_post      no     668      no   no   
45210  37  business  married   no_post      no    2971      no   no   

         contact day month duration campaign pdays previous poutcome  season  
0        unknown   5   may      261        1    -1        0  unknown  spring  
1        unknown   5   may      151        1    -1        0  unknown  spring  
2        unknown   5   may       76        1    -1        0  unknown  spring  
3        unknown   5   may       92        1    -1        0  unknown  spring  
4        unknown   5   may      198        1    -1        0  unknown  spring  
...          ...  ..   ...      ...      ...   ...      ...      ...     ...  
45206   cellular  17   nov      977        3    -1        0  unknown    fall  
45207   cellular  17   nov      456        2    -1        0  unknown    fall  
45208   cellular  17   nov     1127        5   184        3  success    fall  
45209  telephone  17   nov      508        4    -1        0  unknown    fall  
45210   cellular  17   nov      361        2   188       11    other    fall  

[45211 rows x 17 columns]

In [133]:
y

results
0          no
1          no
2          no
3          no
4          no
...       ...
45206     yes
45207     yes
45208     yes
45209      no
45210      no

[45211 rows x 1 columns]

In [99]:
test=pd.get_dummies(x1[['job','marital','education','default','housing','loan','contact','poutcome','season']])
x2=x1.drop(x1[['job','marital','education','default','housing','loan','contact','month','poutcome','season']],axis=1)

x2 = pd.concat([x2, test], axis=1)
#x2 is trimmed column names
x2

age balance day duration campaign pdays previous  job_business  \
0      58    2143   5      261        1    -1        0             1   
1      44      29   5      151        1    -1        0             0   
2      33       2   5       76        1    -1        0             1   
3      47    1506   5       92        1    -1        0             0   
4      33       1   5      198        1    -1        0             0   
...    ..     ...  ..      ...      ...   ...      ...           ...   
45206  51     825  17      977        3    -1        0             0   
45207  71    1729  17      456        2    -1        0             0   
45208  72    5715  17     1127        5   184        3             0   
45209  57     668  17      508        4    -1        0             0   
45210  37    2971  17      361        2   188       11             1   

       job_none  job_other  ...  contact_telephone  contact_unknown  \
0             0          0  ...                  0                1   
1             0          1  ...                  0                1   
2             0          0  ...                  0                1   
3             0          1  ...                  0                1   
4             1          0  ...                  0                1   
...         ...        ...  ...                ...              ...   
45206         0          1  ...                  0                0   
45207         1          0  ...                  0                0   
45208         1          0  ...                  0                0   
45209         0          1  ...                  1                0   
45210         0          0  ...                  0                0   

       poutcome_failure  poutcome_other  poutcome_success  poutcome_unknown  \
0                     0               0                 0                 1   
1                     0               0                 0                 1   
2                     0               0                 0                 1   
3                     0               0                 0                 1   
4                     0               0                 0                 1   
...                 ...             ...               ...               ...   
45206                 0               0                 0                 1   
45207                 0               0                 0                 1   
45208                 0               0                 1                 0   
45209                 0               0                 0                 1   
45210                 0               1                 0                 0   

       season_fall  season_spring  season_summer  season_winter  
0                0              1              0              0  
1                0              1              0              0  
2                0              1              0              0  
3                0              1              0              0  
4                0              1              0              0  
...            ...            ...            ...            ...  
45206            1              0              0              0  
45207            1              0              0              0  
45208            1              0              0              0  
45209            1              0              0              0  
45210            1              0              0              0  

[45211 rows x 31 columns]

In [100]:
x2.shape

(45211, 31)

In [101]:
#Not sure which ones we want to drop I am going to let group decide. 

X=x2.copy(deep=True)


In [102]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=100)

In [103]:
# Decision tree 
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier

In [104]:
for i in range(2,11):
    dtClf = DecisionTreeClassifier(random_state = 100,max_leaf_nodes=i)
    dtClf.fit(X_train, y_train)
    y_pred = dtClf.predict(X_test)
    cm = metrics.confusion_matrix(y_test, y_pred)
    score = (cm[1,1])/(cm[1,1]+cm[1,0])
    #Returns the best recall score from this model
    print(score)

0.0
0.15009499683343888
0.15009499683343888
0.15009499683343888
0.34642178594046863
0.34642178594046863
0.32425585813806207
0.3394553514882837
0.357188093730209


In [105]:
for i in range(1,10):
    dtClf = DecisionTreeClassifier(random_state = 100,max_depth=i,max_leaf_nodes=10)
    dtClf.fit(X_train, y_train)
    y_pred = dtClf.predict(X_test)
    cm = metrics.confusion_matrix(y_test, y_pred)
    score = (cm[1,1])/(cm[1,1]+cm[1,0])
    #Returns the best recall score from this model
    print(score)

0.0
0.34642178594046863
0.2963901203293224
0.34198860037998735
0.34198860037998735
0.357188093730209
0.357188093730209
0.357188093730209
0.357188093730209


In [107]:
dtClf = DecisionTreeClassifier(random_state = 100,max_depth=6,max_leaf_nodes=10)
dtClf.fit(X_train, y_train)
y_pred = dtClf.predict(X_test)

y_pred

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [108]:
cm = metrics.confusion_matrix(y_test, y_pred)
score = (cm[1,1])/(cm[1,1]+cm[1,0])
scoreList.append(score)
print(cm)
print('The number of people who take the offer as predicted is ',cm[1,1], 'with ratio of ',round(score,4)*100,'%.')

[[11625   360]
 [ 1015   564]]
The number of people who take the offer as predicted is  564 with ratio of  35.72 %.


print('The accuracy score is: ',metrics.accuracy_score(y_test, y_pred))
print('The precision score is: ',metrics.precision_score(y_test, y_pred,pos_label='yes'))
print('The recall score is: ',metrics.recall_score(y_test, y_pred,pos_label='yes'))
# this is the result with dammies
#tree.plot_tree(dtClf)

In [109]:
from sklearn.neighbors import KNeighborsClassifier

In [110]:
#Determining the n_neighbors parameter
#Cannot necessairly do grid search/random search since that would be too much for my computer.
for i in range(2,15):
    knnClf = KNeighborsClassifier(n_neighbors = i) 
    knnClf.fit(X_train,y_train)
    y_pred = knnClf.predict(X_test)
    cm = metrics.confusion_matrix(y_test, y_pred)
    score = (cm[1,1])/(cm[1,1]+cm[1,0])
    #Returns the best recall score from this model
    print(score)

0.14692843571880937
0.2982900569981001
0.1830272324255858
0.27485750474984166
0.1861937935402153
0.2577580747308423
0.18556048131728942
0.24509183027232426
0.18682710576314124
0.2324255858138062
0.17479417352754908
0.21659278024065864
0.16656111462951234


In [111]:

knnClf = KNeighborsClassifier(n_neighbors = 2) 
knnClf.fit(X_train,y_train)
y_pred = knnClf.predict(X_test)

y_pred

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [112]:
cm = metrics.confusion_matrix(y_test, y_pred)
score = (cm[1,1])/(cm[1,1]+cm[1,0])
scoreList.append(score)
print(cm)
print('The number of people correctly predicted is ',(cm[1,1]), 'with an recall of ',round(score,4)*100,'%.')

[[11689   296]
 [ 1347   232]]
The number of people correctly predicted is  232 with an recall of  14.69 %.


In [113]:
# GradientBoosting
from sklearn.ensemble import GradientBoostingClassifier
gradient_booster = GradientBoostingClassifier(learning_rate=0.1,random_state=100)
gradient_booster.fit(X_train,y_train)
y_pred = gradient_booster.predict(X_test)

y_pred

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [114]:
cm = metrics.confusion_matrix(y_test, y_pred)
score = (cm[1,1])/(cm[1,1]+cm[1,0])
scoreList.append(score)
print(cm)
print('The number of people correctly predicted is ',(cm[1,1]), 'with an recall of ',round(score,4)*100,'%.')

[[11639   346]
 [  960   619]]
The number of people correctly predicted is  619 with an recall of  39.2 %.


In [115]:
from sklearn.ensemble import RandomForestClassifier

In [118]:
for i in range(20,30):
    rf = RandomForestClassifier(random_state=100,max_depth=i)
    rf.fit(X_train, y_train)
    y_pred = rf.predict(X_test)
    cm = metrics.confusion_matrix(y_test, y_pred)
    score = (cm[1,1])/(cm[1,1]+cm[1,0])
    print(score)

0.3641545281823939
0.3654211526282457
0.36858771374287524
0.3647878404053198
0.3654211526282457
0.3584547181760608
0.363521215959468
0.36732108929702345
0.3654211526282457
0.3616212792906903


In [123]:

rf = RandomForestClassifier(random_state=100,max_depth=25)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

In [124]:
cm = metrics.confusion_matrix(y_test, y_pred)
score = (cm[1,1])/(cm[1,1]+cm[1,0])
scoreList.append(score)
print(cm)
print('The number of people correctly predicted is ',(cm[1,1]), 'with an recall of ',round(score,4)*100,'%.')

[[11660   325]
 [ 1013   566]]
The number of people correctly predicted is  566 with an recall of  35.85 %.


In [125]:
# logistic regression
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=100)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

y_pred

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [126]:
cm = metrics.confusion_matrix(y_test, y_pred)
score = (cm[1,1])/(cm[1,1]+cm[1,0])
scoreList.append(score)
print(cm)
print('The number of people correctly predicted is ',(cm[1,1]), 'with an recall of ',round(score,4)*100,'%.')

[[11782   203]
 [ 1292   287]]
The number of people correctly predicted is  287 with an recall of  18.18 %.


In [127]:
# svm
from sklearn import svm
svmclf =svm.SVC()
svmclf.fit(X_train, y_train)

y_pred = svmclf.predict(X_test)

y_pred

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype=object)

In [128]:
cm = metrics.confusion_matrix(y_test, y_pred)
score = (cm[1,1])/(cm[1,1]+cm[1,0])
scoreList.append(score)
print(cm)
print('The number of people correctly predicted is ',(cm[1,1]), 'with an recall of ',round(score,4)*100,'%.')

[[11971    14]
 [ 1568    11]]
The number of people correctly predicted is  11 with an recall of  0.7000000000000001 %.


In [129]:
# vaive bayers
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train,y_train)
y_pred = gnb.predict(X_test)
y_pred

array(['no', 'no', 'no', ..., 'no', 'no', 'no'], dtype='<U3')

In [130]:
cm = metrics.confusion_matrix(y_test, y_pred)
score = (cm[1,1])/(cm[1,1]+cm[1,0])
scoreList.append(score)
print(cm)
print('The number of people correctly predicted is ',(cm[1,1]), 'with an recall of ',round(score,4)*100,'%.')

[[9788 2197]
 [ 667  912]]
The number of people correctly predicted is  912 with an recall of  57.76 %.


In [131]:
max(scoreList) # Vaive bayers model best fit

0.577580747308423

In [132]:
scoreList

[0.357188093730209,
 0.14692843571880937,
 0.39202026599113365,
 0.3584547181760608,
 0.181760607979734,
 0.3584547181760608,
 0.181760607979734,
 0.006966434452184927,
 0.577580747308423]